# Keyboard Layout Scorer Configuration
# This file defines default settings and data file paths for all scoring methods

common:
  # Common settings across all scorers
  default_output_format: "detailed"  # detailed, csv, score-only
  letter_filtering: true  # Only analyze alphabetic characters
  quiet_mode: false
  
  # Default data directory structure
  data_directories:
    base: "input/"
    engram: "input/engram/"
    dvorak9: "input/dvorak9/"
    distance: "input/distance/"

# Physical distance-based scoring
distance_scorer:
  description: "Physical finger travel distance analysis"
  method: "Euclidean distance between key positions on staggered keyboard"
  
  data_files:
    # Built-in position mapping (no external file needed)
    position_map: null
    
  scoring_options:
    distance_metric: "euclidean"  # euclidean, manhattan
    normalize_by_bigrams: true
    exclude_same_key: true
    
  output:
    primary_score_name: "normalized_score"
    components:
      - "total_distance"
      - "average_distance" 
      - "max_distance"
      - "min_distance"
      - "coverage"
    
  validation:
    min_coverage: 0.8  # Minimum bigram coverage required
    min_text_length: 10  # Minimum text length for analysis

# Dvorak's 9 evaluation criteria
dvorak9_scorer:
  description: "Dvorak's 9 theoretical typing principles with empirical validation"
  method: "Frequency-weighted evaluation of hand alternation, finger usage, etc."
  
  data_files:
    frequencies: "normalized_letter_pair_frequencies_en.csv"
    key_pair_scores: "key_pair_scores.csv"
    speed_weights: "speed_weights.csv"  # optional
    comfort_weights: "comfort_weights.csv"  # optional
    
  scoring_options:
    # Available scoring approaches
    approaches: 
      - "pure_dvorak"        # Unweighted average of 9 criteria
      - "frequency_weighted" # English bigram frequency-weighted
      - "empirically_weighted" # Real performance data weighted
    
    default_approach: "frequency_weighted"
    
    # Individual criteria (all 0-1 scale, higher = better)
    criteria:
      hands: "Favor alternating hands over same hand"
      fingers: "Avoid same finger repetition"
      skip_fingers: "Favor non-adjacent fingers over adjacent"
      dont_cross_home: "Avoid crossing over the home row"
      same_row: "Favor typing within the same row"
      home_row: "Favor using the home row"
      columns: "Favor fingers staying in designated columns"
      strum: "Favor inward rolls over outward rolls"
      strong_fingers: "Favor stronger fingers over weaker ones"
      
  output:
    primary_score_name: "layout_score"
    components:
      - "pure_dvorak_score"
      - "frequency_weighted_score"
      - "hands"
      - "fingers" 
      - "skip_fingers"
      - "dont_cross_home"
      - "same_row"
      - "home_row"
      - "columns"
      - "strum"
      - "strong_fingers"
      
  validation:
    min_bigram_coverage: 0.9
    required_criteria_count: 9

# Engram frequency and comfort-based scoring  
engram_scorer:
  description: "Letter frequency and key comfort combination scoring"
  method: "Multiplicative combination of item frequencies and position comfort"
  
  data_files:
    item_scores: "normalized_letter_frequencies_en.csv"
    item_pair_scores: "normalized_letter_pair_frequencies_en.csv"
    position_scores: "normalized_key_comfort_scores_32keys.csv"
    position_pair_scores: "normalized_key_pair_comfort_scores_32keys_LvsRpairs.csv"
    
  scoring_options:
    # How to combine item and item-pair scores
    combination_strategy: "multiplicative"  # multiplicative, additive, weighted_additive
    
    # Weighted additive parameters (if using weighted_additive)
    item_weight: 0.6
    item_pair_weight: 0.4
    
    # Normalization method for input data
    normalization_method: "auto"  # auto, robust, linear, sqrt
    
    # Cross-hand filtering options
    ignore_cross_hand: false
    
  output:
    primary_score_name: "total_score"
    components:
      - "item_component"
      - "item_pair_component"
      
  validation:
    min_items: 5
    max_items: 32
    min_alphabet_coverage: 0.5  # Minimum coverage of standard alphabet
    
# Output formatting options
output_formats:
  csv:
    delimiter: ","
    include_headers: true
    precision: 6
    
  detailed:
    show_breakdown: true
    show_validation_info: true
    show_file_sources: true
    
  score_only:
    precision: 6
    separator: " "  # For multiple scores

# CLI argument standardization
cli:
  # Standard argument names across all scorers
  layout_args:
    letters: ["--layout-letters", "--letters"]  # aliases
    positions: ["--layout-positions", "--positions", "--qwerty-keys"]
    
  input_args:
    data_dir: ["--data-dir", "--input-dir"]
    config_file: ["--config", "--config-file"]
    text_file: ["--text-file", "--text"]  # for distance scorer
    
  output_args:
    format: ["--output-format", "--format"]
    csv: ["--csv"]
    detailed: ["--detailed", "--details"]
    score_only: ["--score-only", "--scores-only"]
    quiet: ["--quiet", "-q"]
    
  scorer_specific:
    weights: ["--weights", "--weights-file"]  # for dvorak9
    ignore_cross_hand: ["--ignore-cross-hand"]  # for engram

# Future scorer template
template_scorer:
  description: "Template for adding new scoring methods"
  method: "Description of the scoring approach"
  
  data_files:
    # Required data files
    required_file: "filename.csv"
    
  scoring_options:
    # Scorer-specific options
    example_option: "default_value"
    
  output:
    primary_score_name: "score"
    components: []
    
  validation:
    # Validation requirements
    min_coverage: 0.8